import React,{useEffect,useRef,useState} from 'react';
import {Check,ExternalLink,LoaderCircle,LogOut} from 'lucide-react';
import {call,native} from './bridge';
import type {Account} from './model';
type Device={id:string;code:string;interval:number;expiresIn:number;url:string};
export function AccountControls({account,onAccount}:{account:Account|null;onAccount:(a:Account|null)=>Promise<void>}){
 const [configured,setConfigured]=useState<boolean|null>(null),[clientId,setClientId]=useState(''),[device,setDevice]=useState<Device|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[name,setName]=useState(account?.type==='local'?account.name:''),[copied,setCopied]=useState(false);
 const alive=useRef(true);
 useEffect(()=>{alive.current=true;if(native)call<{configured:boolean}>('auth_info').then(v=>{if(alive.current)setConfigured(v.configured)}).catch(e=>{if(alive.current)setError(String(e))});else setConfigured(false);return()=>{alive.current=false;if(native)void call('auth_cancel').catch(()=>{})}} ,[]);
 useEffect(()=>{if(!device)return;let stopped=false,timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const r=await call<{status:string;account?:Account}>('auth_poll',{id:device.id});if(stopped||!alive.current)return;if(r.status==='complete'&&r.account){setDevice(null);await onAccount(r.account);return;}timer=setTimeout(poll,device.interval*1000);}catch(e){if(!stopped&&alive.current){setError(String(e));setDevice(null);}}};timer=setTimeout(poll,device.interval*1000);return()=>{stopped=true;clearTimeout(timer)}},[device]);
 const run=async(fn:()=>Promise<void>)=>{setError('');setBusy(true);try{await fn()}catch(e){if(alive.current)setError(String(e))}finally{if(alive.current)setBusy(false)}};
 return <div className="account-options">
  {account?.type==='microsoft'&&<div className="setting"><div><strong>{account.name}</strong><small><Check size={13}/> Microsoft · Java Edition</small></div><button className="secondary" onClick={()=>run(async()=>{await call('auth_sign_out');await onAccount(null)})}><LogOut size={16}/>Sign out</button></div>}
  {device?<section className="device-signin" aria-label="Microsoft authorization"><p>Enter this code on Microsoft's website.</p><button className="device-code" aria-label="Copy sign-in code" onClick={()=>run(async()=>{await navigator.clipboard.writeText(device.code);setCopied(true)})}>{device.code}</button><small>{copied?'Copied':'Click to copy'}</small><button className="primary" onClick={()=>run(async()=>{await call('auth_open')})}>Open Microsoft <ExternalLink size={16}/></button><p role="status"><LoaderCircle className="spin" size={16}/> Waiting for authorization</p><button className="secondary" onClick={()=>run(async()=>{await call('auth_cancel');setDevice(null)})}>Cancel sign-in</button></section>:<button className="primary microsoft-signin" disabled={!native||!configured||busy} onClick={()=>run(async()=>{const d=await call<Device>('auth_begin');if(alive.current)setDevice(d);})}>{busy?<LoaderCircle className="spin" size={18}/>:<span className="ms-mark"/>}Sign in with Microsoft</button>}
  {native&&configured&&!device&&<button className="secondary" onClick={()=>setConfigured(false)}>Application setup</button>}
  {!native&&<p className="context-note">Microsoft sign-in is available in the desktop app.</p>}
  {native&&configured===false&&<div className="registration-setup"><strong>Application setup required</strong><p>Add Unbox's registered Microsoft Client ID to enable sign-in.</p><label>Application (client) ID<input placeholder="00000000-0000-0000-0000-000000000000" value={clientId} onChange={e=>setClientId(e.target.value.trim())}/></label><button className="secondary" disabled={busy||!clientId} onClick={()=>run(async()=>{await call('auth_setup',{clientId});setConfigured(true)})}>Save Client ID</button><small>Public client flow and Minecraft Services approval are required. No client secret.</small></div>}
  {error&&<p className="error" role="alert">{error}</p>}
  {!device&&<details className="local-account"><summary>Local play</summary><p>Singleplayer and private servers that allow offline accounts.</p><label>Player name<input placeholder="Player" value={name} maxLength={16} onChange={e=>setName(e.target.value)}/></label><button className="secondary" disabled={busy||!/^[A-Za-z0-9_]{1,16}$/.test(name)} onClick={()=>run(()=>onAccount({name,type:'local'}))}>Use local account</button></details>}
 </div>
}
