import React,{useEffect,useRef,useState} from 'react';
import {Check,ExternalLink,LoaderCircle,LogOut,Box,Pencil} from 'lucide-react';
import {call,native} from './bridge';
import type {Account} from './model';
import {UnboxAccount} from './UnboxAccount';
import {SkinFace} from './SkinPreview';
export type AccountSnapshot={accounts:Account[];account:Account|null};
type Info={configured:boolean;clientId?:string;provider?:string;developmentAvailable?:boolean};
type Device={id:string;code:string;interval:number;expiresIn:number;url:string;provider?:string};
export function AccountControls({account,onAccount}:{account:Account|null;onAccount:(a:Account|null,close?:boolean)=>Promise<void>}){
 const [info,setInfo]=useState<Info|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[setup,setSetup]=useState(false),[clientId,setClientId]=useState(''),[device,setDevice]=useState<Device|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[name,setName]=useState(account?.type==='local'?account.name:''),[copied,setCopied]=useState(false),[remaining,setRemaining]=useState(0),[message,setMessage]=useState('Waiting for authorization');
 const [unboxEditing,setUnboxEditing]=useState(false),[renaming,setRenaming]=useState<string|null>(null),[playerName,setPlayerName]=useState('');
 const alive=useRef(true),onAccountRef=useRef(onAccount),deadline=useRef(0);onAccountRef.current=onAccount;
 const apply=async(s:AccountSnapshot,close=false)=>{setAccounts(s.accounts);await onAccountRef.current(s.account,close)};
 useEffect(()=>{alive.current=true;if(native){Promise.all([call<Info>('auth_info'),call<AccountSnapshot>('auth_accounts')]).then(async([i,s])=>{if(!alive.current)return;setInfo(i);setClientId(i.clientId||'');setAccounts(s.accounts);setSetup(!i.configured);await onAccountRef.current(s.account,false)}).catch(e=>{if(alive.current)setError(String(e))});}else setInfo({configured:false});return()=>{alive.current=false;if(native)void call('auth_cancel').catch(()=>{})}},[]);
 useEffect(()=>{
  if(!device)return;let stopped=false,timer:ReturnType<typeof setTimeout>;
  const poll=async()=>{try{const r=await call<AccountSnapshot&{status:string;interval?:number;message?:string}>('auth_poll',{id:device.id});if(stopped||!alive.current)return;if(r.status==='complete'){setDevice(null);await apply(r,true);return;}setMessage(r.message||'Waiting for authorization');timer=setTimeout(poll,(r.interval||device.interval)*1000);}catch(e){if(!stopped&&alive.current){setError(String(e));setDevice(null);}}};
  timer=setTimeout(poll,device.interval*1000);const tick=setInterval(()=>{const seconds=Math.max(0,Math.ceil((deadline.current-Date.now())/1000));setRemaining(seconds);if(!seconds){stopped=true;clearTimeout(timer);setDevice(null);setError('Sign-in code expired. Start again.');void call('auth_cancel').catch(()=>{})}},1000);
  return()=>{stopped=true;clearTimeout(timer);clearInterval(tick)};
 },[device]);
 const run=async(fn:()=>Promise<void>)=>{if(busy)return;setError('');setBusy(true);try{await fn()}catch(e){if(alive.current)setError(String(e))}finally{if(alive.current)setBusy(false)}};
 const configured=async(cmd:string,args:Record<string,unknown>={})=>{const snapshot=await call<AccountSnapshot>(cmd,args);await apply(snapshot);const i=await call<Info>('auth_info');setInfo(i);setClientId(i.clientId||'');setSetup(false)};
 return <div className="account-options">
  {!device&&<UnboxAccount onEditing={setUnboxEditing} onComplete={async snapshot=>apply(snapshot,true)}/>}
  {!unboxEditing&&<>
  {!device&&accounts.length>0&&<div className="saved-accounts" aria-label="Saved accounts">{accounts.map(a=><div className={`saved-account ${a.accountId===account?.accountId?'selected':''}`} key={a.accountId}>
   <button className="account-choice" disabled={busy} aria-label={`Use ${a.name} · ${a.provider}`} onClick={()=>run(async()=>apply(await call<AccountSnapshot>('auth_select',{accountId:a.accountId}),true))}><span className="avatar">{a.skin?<SkinFace skin={a.skin}/>:<Box size={19}/>}</span><span><strong>{a.name}</strong><small>{a.needsSignIn?'Sign in again':a.provider||'Microsoft · Java Edition'}</small></span>{a.accountId===account?.accountId&&<Check size={17}/>}</button>
   {a.type==='unbox'&&<button className="icon-btn" disabled={busy} aria-label={`Rename ${a.name}`} title="Change player name" onClick={()=>{setRenaming(a.accountId||null);setPlayerName(a.name);setError('')}}><Pencil size={16}/></button>}
   <button className="icon-btn remove-account" disabled={busy} aria-label={`Remove ${a.name} · ${a.provider}`} title="Remove account from this Mac" onClick={()=>run(async()=>apply(await call<AccountSnapshot>('auth_sign_out',{accountId:a.accountId})))}><LogOut size={17}/></button>
  </div>)}</div>}
  {renaming&&<form className="unbox-signin" aria-label="Change player name" onSubmit={e=>{e.preventDefault();void run(async()=>{await apply(await call<AccountSnapshot>('auth_unbox_rename',{accountId:renaming,name:playerName.trim()}));setRenaming(null)})}}><label>Player name<input autoFocus required pattern="[A-Za-z0-9_]{3,16}" minLength={3} maxLength={16} value={playerName} disabled={busy} onChange={e=>setPlayerName(e.target.value)}/></label><small>Names can be shared. Your account, friends and worlds stay the same.</small><button type="submit" className="primary" disabled={busy}>Save name</button><button type="button" className="text-button" disabled={busy} onClick={()=>setRenaming(null)}>Cancel</button></form>}
  {device?<section className="device-signin" aria-label="Microsoft authorization"><small>{device.provider||info?.provider}</small><p>Enter this code on Microsoft's website.</p><button className="device-code" aria-label="Copy sign-in code" onClick={()=>run(async()=>{await navigator.clipboard.writeText(device.code);setCopied(true)})}>{device.code}</button><small>{copied?'Copied':'Click to copy'} · Expires in {Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</small><button className="primary" disabled={busy} onClick={()=>run(async()=>{await call('auth_open')})}>Open Microsoft <ExternalLink size={16}/></button><p role="status"><LoaderCircle className="spin" size={16}/>{message}</p><button className="secondary" disabled={busy} onClick={()=>run(async()=>{await call('auth_cancel');setDevice(null)})}>Cancel sign-in</button></section>:<button className="primary microsoft-signin" disabled={!native||!info?.configured||busy} onClick={()=>run(async()=>{setCopied(false);setMessage('Waiting for authorization');const d=await call<Device>('auth_begin');if(alive.current){deadline.current=Date.now()+d.expiresIn*1000;setRemaining(d.expiresIn);setDevice(d);}})}>{busy?<LoaderCircle className="spin" size={18}/>:<span className="ms-mark"/>}Sign in with Microsoft</button>}
  {!device&&native&&info?.configured&&<div className="account-provider"><small>{info.provider} · Secure account storage</small><button disabled={busy} className="text-button" onClick={()=>setSetup(!setup)}>Application setup</button></div>}
  {!native&&<p className="context-note">Microsoft sign-in is available in the desktop app.</p>}
  {native&&setup&&!device&&<div className="registration-setup"><strong>Login application</strong><label>Unbox application (client) ID<input placeholder="00000000-0000-0000-0000-000000000000" value={clientId} onChange={e=>setClientId(e.target.value.trim())}/></label><button className="secondary" disabled={busy||!clientId} onClick={()=>run(()=>configured('auth_setup',{clientId}))}>Save Client ID</button><small>Changing the application requires a new sign-in. Saved accounts are kept.</small>{info?.developmentAvailable&&<><button className="secondary" disabled={busy} onClick={()=>run(()=>configured('auth_development_setup'))}>Use DevLogin for development</button><small>Local development only. Microsoft authorization identifies DevLogin. This option is excluded from release builds.</small></>}</div>}
  {error&&<p className="error" role="alert">{error}</p>}
  {!device&&<details className="local-account"><summary>Local play</summary><p>Singleplayer and private servers that allow offline accounts.</p><label>Player name<input placeholder="Player" value={name} maxLength={16} onChange={e=>setName(e.target.value)}/></label><button className="secondary" disabled={busy||!/^[A-Za-z0-9_]{1,16}$/.test(name)} onClick={()=>run(async()=>{if(native)await apply(await call<AccountSnapshot>('auth_local',{name}),true);else await onAccount({name,type:'local'})})}>Use local account</button></details>}
 </>}
 </div>
}
