import {BrandMark} from './BrandMark';
import React,{useEffect,useRef,useState} from 'react';
import {Plus,Check,X,Copy,UserPlus,Box,Send,LogIn,LoaderCircle} from 'lucide-react';
import {call,native} from './bridge';
type Friend={id:string;name:string;code:string;face?:string;online:boolean;state:string;accepted:number;direction:string;kind:string};
type Invite={id:string;receiver:string;senderName:string;expires:number;room:{name:string}};
type View={connected:boolean;self?:{id:string;code:string};friends:Friend[];invites:Invite[];error?:string;canInvite?:boolean;gameError?:string};
export function Friends(){
 const [view,setView]=useState<View>({connected:false,friends:[],invites:[]}),[add,setAdd]=useState(false),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const live=useRef(true);
 useEffect(()=>{live.current=true;const refresh=()=>{if(native)call<View>('social_status').then(v=>{if(live.current&&v)setView(v)}).catch(e=>{if(live.current)setError(String(e))})};refresh();const t=setInterval(refresh,2000);return()=>{live.current=false;clearInterval(t)}},[]);
 const action=async(op:string,id:string)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{const v=await call<View>('social_action',{op,id});if(live.current){setView(v);if(op==='request'){setCode('');setAdd(false);setNotice('Friend request sent')}if(op==='invite')setNotice('Preparing invitation…');if(op==='join')setNotice('Syncing your friend’s mods; the game may restart…');}}catch(e){if(live.current)setError(String(e))}finally{if(live.current)setBusy(false)}};
 const friends=view.friends||[],invites=(view.invites||[]).filter(i=>i.receiver===view.self?.id&&i.expires>Date.now());
 return <aside className="friends"><header><h3>FRIENDS</h3><button className="icon-btn" aria-label="Add friend" title="Add friend" onClick={()=>setAdd(!add)}><Plus size={20}/></button></header>
 {view.self&&<button className="friend-code" title="Copy your friend code" onClick={()=>navigator.clipboard.writeText(view.self!.code).then(()=>setNotice('Friend code copied')).catch(()=>setError('Could not copy code'))}>{view.self.code}<Copy size={12}/></button>}
 {add&&<form className="friend-add" onSubmit={e=>{e.preventDefault();void action('request',code)}}><label>Friend code<input autoFocus aria-label="Friend code" placeholder="12-character code" maxLength={12} value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-F0-9]/g,''))}/></label><button className="icon-btn" title="Send friend request" aria-label="Send friend request" disabled={!view.connected||busy||code.length!==12}><UserPlus size={18}/></button></form>}
 {!view.connected&&<p className="friend-service" role="status">{view.error||'Open the desktop app to connect friends.'}</p>}
 {view.connected&&friends.length===0&&!invites.length&&<p className="friend-service">Share your code or add a friend.</p>}
 <div className="friend-rows">{invites.map(i=><div className="world-invite" key={i.id}><div><strong>{i.senderName}</strong><small>{i.room.name}</small></div><button disabled={busy} className="icon-btn" title="Join world · sync mods and restart if needed" aria-label={`Join ${i.senderName}'s world`} onClick={()=>action('join',i.id)}><LogIn size={19}/></button><button disabled={busy} className="icon-btn" title="Dismiss invitation" aria-label="Dismiss invitation" onClick={()=>action('dismiss',i.id)}><X size={14}/></button></div>)}
 {friends.map(f=><div className="friend-row" key={f.id}><span className="friend-face">{f.face?<img src={f.face} alt=""/>:<Box size={24}/>}<i className={f.online?'online':''}/></span><div className="friend-label" title={`${f.name} · ${f.code}`}><strong><BrandMark className="friend-badge" surface="var(--panel)" strokeWidth={2.4} decorative/>{f.name}</strong><small>{f.accepted?(f.online?f.state:'Offline'):f.direction==='incoming'?'Friend request':'Request sent'}</small></div>{!f.accepted&&f.direction==='incoming'?<button disabled={busy} className="icon-btn" aria-label={`Accept ${f.name}`} title="Accept friend" onClick={()=>action('accept',f.id)}><Check size={18}/></button>:f.accepted?<button disabled={busy||!view.canInvite||!f.online||!['microsoft','unbox'].includes(f.kind)} className="friend-invite" title={!['microsoft','unbox'].includes(f.kind)?'Verified account required':view.canInvite?'Invite to your world':'Open a singleplayer world to invite'} onClick={()=>action('invite',f.id)}>Invite<Send size={12}/></button>:null}<button disabled={busy} className="icon-btn friend-remove" aria-label={`Remove ${f.name}`} title="Remove friend" onClick={()=>action('remove',f.id)}><X size={13}/></button></div>)}
 </div>{busy&&<LoaderCircle className="spin" size={14}/>} {notice&&<p role="status" className="friend-notice">{notice}</p>}{error&&<p role="alert" className="error">{error}</p>}{view.gameError&&<p className="friend-notice">{view.gameError}</p>}
 </aside>
}
