import React,{useState} from 'react';
import catalogue from './mod-options.json';
import type {Config} from './model';
type Option={key:string;label:string;kind:string;fallback:string;min:number;max:number;choices?:string[]};
const modules=catalogue.modules as unknown as Record<string,Record<string,Option[]|Record<string,Option[]>>>;
const presets=['Fine cross','Open cross','Dot','Ring','Square','Chevron','Diagonal','Diamond'];
function pattern(index:number){return Array.from({length:225},(_,i)=>{const x=i%15,y=Math.floor(i/15),dx=Math.abs(x-7),dy=Math.abs(y-7);return (index===0?(dx===0&&dy<=5||dy===0&&dx<=5):index===1?(dx===0&&dy>=3&&dy<=6||dy===0&&dx>=3&&dx<=6):index===2?dx<=1&&dy<=1:index===3?dx*dx+dy*dy>=18&&dx*dx+dy*dy<=28:index===4?Math.max(dx,dy)===5:index===5?y>=5&&y<=10&&dx===y-5:index===6?dx===dy&&dx>=2&&dx<=5:dx+dy===5)?'1':'0'}).join('')}
function keyLabel(n:number){if(n===-1)return 'Unbound';if(n>=65&&n<=90||n>=48&&n<=57)return String.fromCharCode(n);if(n>=290&&n<=314)return 'F'+(n-289);return ({32:'Space',257:'Enter',258:'Tab',259:'Backspace',262:'Right',263:'Left',264:'Down',265:'Up',340:'Left Shift',341:'Left Control',342:'Left Alt',344:'Right Shift',345:'Right Control',346:'Right Alt'} as Record<number,string>)[n]||`Key ${n}`}
function keyCode(e:React.KeyboardEvent){if(e.code.startsWith('Key'))return e.code.charCodeAt(3);if(e.code.startsWith('Digit'))return e.code.charCodeAt(5);if(/^F\d+$/.test(e.code))return 289+Number(e.code.slice(1));return ({Space:32,Tab:258,Enter:257,Backspace:259,ArrowRight:262,ArrowLeft:263,ArrowDown:264,ArrowUp:265,ShiftLeft:340,ControlLeft:341,AltLeft:342,ShiftRight:344,ControlRight:345,AltRight:346,Backquote:96,Minus:45,Equal:61,BracketLeft:91,BracketRight:93,Backslash:92,Semicolon:59,Quote:39,Comma:44,Period:46,Slash:47} as Record<string,number>)[e.code]}
export function ModSettings({id,config,set,patch}:{id:string;config:Config;set:(key:string,value:string|number|boolean)=>unknown;patch:(values:Config)=>Promise<void>}){
 const [tab,setTab]=useState('General'),[query,setQuery]=useState(''),[recording,record]=useState(false),[notice,note]=useState('');
 const definition=modules[id]||{};const tabs=Object.keys(definition).filter(t=>t!=='families');const active=tabs.includes(tab)?tab:'General';
 const family=String(config['particles.family']||'Critical');const byTab=(t:string)=>(t==='Types'&&id==='particles'?(definition.families as Record<string,Option[]>)[family]:definition[t]) as Option[]||[];
 const options=(query?tabs.flatMap(byTab).filter(o=>(o.label+' '+o.key).toLowerCase().includes(query.toLowerCase())):byTab(active)).filter((o,i,a)=>a.findIndex(v=>v.key===o.key)===i);
 const value=(o:Option)=>config[o.key]??(o.kind==='toggle'?o.fallback==='true':o.kind==='slider'?Number(o.fallback):o.fallback);
 const pixels=/^[01]{225}$/.test(String(config['crosshair.pixels']))?String(config['crosshair.pixels']):'0'.repeat(225);
 return <div className="mod-settings-catalogue"><input className="settings-search" placeholder="Search settings…" aria-label="Search module settings" value={query} onChange={e=>setQuery(e.target.value)}/><div className="filters" role="tablist" aria-label="Module settings">{tabs.map(t=><button role="tab" aria-selected={active===t} className={active===t?'active':''} key={t} onClick={()=>{setTab(t);setQuery('')}}>{t}</button>)}</div>
 {options.map(o=><label className="setting" key={o.key} data-setting={o.key}><strong>{o.label}</strong>{o.kind==='toggle'?<button type="button" role="switch" aria-label={o.label} aria-checked={Boolean(value(o))} className={`toggle ${value(o)?'on':''}`} onClick={()=>set(o.key,!value(o))}><span/></button>:o.kind==='choice'?<select aria-label={o.label} value={String(value(o))} onChange={e=>set(o.key,e.target.value)}>{o.choices!.map(c=><option key={c}>{c}</option>)}</select>:o.kind==='color'?<input type="color" aria-label={o.label} value={String(value(o))} onChange={e=>set(o.key,e.target.value.toUpperCase())}/>:<input className="option-number" type="number" aria-label={o.label} min={o.min} max={o.max} value={Number(value(o))} onChange={e=>{if(e.target.value!==''&&Number.isFinite(e.target.valueAsNumber))set(o.key,Math.max(o.min,Math.min(o.max,Math.round(e.target.valueAsNumber))))}}/>}</label>)}
 {!query&&id==='crosshair'&&active==='Presets'&&<div className="crosshair-presets">{presets.map((name,i)=><button className="secondary" key={name} onClick={()=>patch({'crosshair.pixels':pattern(i),'crosshair.shape':'Custom'})}><span className="crosshair-pixels">{Array.from(pattern(i),(c,n)=><i key={n} className={c==='1'?'lit':''}/>)}</span>{name}</button>)}</div>}
 {!query&&id==='crosshair'&&active==='Canvas'&&<><div className="crosshair-editor" aria-label="Crosshair canvas">{Array.from(pixels,(c,i)=><button aria-label={`Pixel ${i%15+1}, ${Math.floor(i/15)+1}`} aria-pressed={c==='1'} key={i} className={c==='1'?'lit':''} onClick={()=>{const next=pixels.split(''),x=i%15,y=Math.floor(i/15),v=c==='1'?'0':'1';next[i]=v;if(config['crosshair.mirror']==='Horizontal'||config['crosshair.mirror']==='Both')next[y*15+14-x]=v;if(config['crosshair.mirror']==='Both'){next[(14-y)*15+x]=v;next[(14-y)*15+14-x]=v}void patch({'crosshair.pixels':next.join(''),'crosshair.shape':'Custom'})}}/>)}</div><div className="filters"><button onClick={()=>set('crosshair.pixels','0'.repeat(225))}>Clear</button><button onClick={()=>navigator.clipboard.writeText('UNBOX1:'+pixels).then(()=>note('Copied')).catch(()=>note('Clipboard unavailable'))}>Copy design</button><button onClick={()=>navigator.clipboard.readText().then(v=>/^UNBOX1:[01]{225}$/.test(v)?patch({'crosshair.pixels':v.slice(7),'crosshair.shape':'Custom'}):note('Invalid design')).catch(()=>note('Clipboard unavailable'))}>Paste design</button></div></>}
 {!query&&active==='General'&&['zoom','freelook','minimap'].includes(id)&&<label className="setting"><strong>Keybind</strong><button className="secondary" onClick={()=>record(!recording)} onBlur={()=>record(false)} onKeyDown={e=>{if(!recording)return;e.preventDefault();e.stopPropagation();if(e.key==='Escape'){record(false);return}const code=e.key==='Delete'?-1:keyCode(e);if(code!==undefined){set(id+'.key',code);record(false);note('Saved. The new binding replaces conflicting bindings in game.')}}}>{recording?'Press a key · Esc cancels':Number(config[id+'.key'])===-1?'Unbound':config[id+'.key']?keyLabel(Number(config[id+'.key'])):`Change (${id==='zoom'?'C':id==='minimap'?'M':'Freelook'})`}</button></label>}
 {id==='freelook'&&active==='General'&&<><label className="setting">Activation<select value={String(config['freelook.mode']||'Hold')} onChange={e=>set('freelook.mode',e.target.value)}><option>Hold</option><option>Toggle</option></select></label><label className="setting">Camera<select value={String(config['freelook.camera']||'THIRD_PERSON_BACK')} onChange={e=>set('freelook.camera',e.target.value)}><option>FIRST_PERSON</option><option>THIRD_PERSON_BACK</option><option>THIRD_PERSON_FRONT</option></select></label></>}
 {notice&&<p role="status">{notice}</p>}<button className="secondary" onClick={()=>{const all=[...tabs.flatMap(byTab),...Object.values((definition.families||{}) as Record<string,Option[]>).flat()],values:Config={};for(const o of all)values[o.key]=o.kind==='toggle'?o.fallback==='true':o.kind==='slider'?Number(o.fallback):o.fallback;if(id==='crosshair')values['crosshair.pixels']='0'.repeat(225);void patch(values)}}>Reset settings</button></div>
}
