package dev.unbox.client;
import com.google.gson.*;
import net.minecraft.client.Minecraft;
import net.minecraft.client.Screenshot;
import net.minecraft.client.gui.screens.DisconnectedScreen;
import java.nio.file.*;
import java.util.*;
/** Opt-in isolated two-process gameplay test. Uses the normal invitation and login path. */
final class PrivateWorldSmokeTest {
 private static int step,ticks;private static long begun;private static String inviteId;private static java.util.concurrent.CompletableFuture<Boolean> ownerProbe;private static final List<String> checks=new ArrayList<>();
 private static void finish(Minecraft mc)throws Exception{Screenshot.grab(mc.gameDirectory,"private-world.png",mc.getMainRenderTarget(),1,c->{});Files.writeString(mc.gameDirectory.toPath().resolve("logs/private-world-smoke.json"),new Gson().toJson(Map.of("passed",checks.size(),"checks",checks)));mc.stop();}
 static void tick(Minecraft mc){String role=System.getProperty("unbox.privateSmoke","");if(role.isEmpty())return;if(begun==0)begun=System.currentTimeMillis();if(System.currentTimeMillis()-begun>300000)throw new IllegalStateException("Private world test timeout: "+SocialBridge.message);if(++ticks%20!=0)return;mc.getFramerateLimitTracker().onInputReceived();try{
  if(role.equals("host")){
   if(mc.getSingleplayerServer()==null||mc.player==null||!SocialBridge.flag(SocialBridge.view,"connected"))return;
   if(step==0&&!SocialBridge.rows("friends").isEmpty()){SocialBridge.invite(SocialBridge.text(SocialBridge.rows("friends").getFirst(),"id"));if(!SocialBridge.hosting())throw new IllegalStateException(SocialBridge.message);checks.add("Registered Unbox host publishes a private world through normal Invite");String name=mc.getUser().getName();UUID id=mc.getUser().getProfileId();int port=mc.getSingleplayerServer().getPort();ownerProbe=java.util.concurrent.CompletableFuture.supplyAsync(()->spoofOwner(name,id,port));step=1;}
   if(step==1){var friends=SocialBridge.rows("friends");if(friends.isEmpty())return;UUID uuid=UUID.fromString(SocialBridge.text(friends.getFirst(),"uuid").replaceFirst("(........)(....)(....)(....)(............)","$1-$2-$3-$4-$5"));var peer=mc.getSingleplayerServer().getPlayerList().getPlayer(uuid);if(peer!=null){if(!peer.getGameProfile().name().equals(mc.getUser().getName()))throw new IllegalStateException("Expected matching test names");if(mc.getSingleplayerServer().isSingleplayerOwner(peer.nameAndId()))throw new IllegalStateException("Same-name guest acquired owner identity");checks.add("Same-name host and guest coexist with distinct UUIDs and separate owner privileges");checks.add("Guest joined with stable cloud UUID, not a nickname-derived identity");Files.writeString(mc.gameDirectory.toPath().resolve("logs/guest-joined.json"),"{}");step=2;}}
   if(step==2&&Files.exists(mc.gameDirectory.toPath().resolve("logs/guest-complete.json"))){if(!ownerProbe.join())throw new IllegalStateException("Owner spoof was not rejected");checks.add("Raw remote client cannot impersonate the world owner identity");checks.add("Guest received world data and completed gameplay ticks");SocialBridge.stopSharing();checks.add("Host can stop sharing after actual guest login");finish(mc);step=3;}
  }else{
   if(step==0&&!SocialBridge.rows("invites").isEmpty()&&SocialBridge.flag(SocialBridge.view,"connected")){JsonObject invite=SocialBridge.rows("invites").getFirst();inviteId=SocialBridge.text(invite,"id");String secret=SocialBridge.text(invite,"join_secret");invite.addProperty("join_secret","0".repeat(64));SocialBridge.join(inviteId);invite.addProperty("join_secret",secret);step=1;}
   else if(step==1&&mc.screen instanceof DisconnectedScreen){checks.add("Wrong invitation secret is rejected by real encrypted login");step=2;}
   else if(step==2){SocialBridge.join(inviteId);step=3;}
   else if(step==3&&mc.player!=null&&mc.level!=null&&mc.getSingleplayerServer()==null){if(!mc.player.getUUID().equals(mc.getUser().getProfileId()))throw new IllegalStateException("Guest UUID changed");if(Boolean.getBoolean("unbox.syncFixture")&&!net.fabricmc.loader.api.FabricLoader.getInstance().isModLoaded("unbox_sync_fixture"))throw new IllegalStateException("Shared gameplay mod did not load after restart");checks.add("Guest enters the host world with its registered identity");if(Boolean.getBoolean("unbox.syncFixture")){if(!net.minecraft.core.registries.BuiltInRegistries.ITEM.containsKey(net.minecraft.resources.Identifier.fromNamespaceAndPath("unbox_sync_fixture","shared_item")))throw new IllegalStateException("Shared item is not registered on guest");checks.add("Transferred gameplay JAR and its custom item registry entry load after native preparation and restart");}step=4;ticks=0;}
   else if(step==4&&ticks>=100){checks.add("Guest stays connected and receives playable world data for 100 ticks");finish(mc);step=5;}
  }
 }catch(Exception e){throw new RuntimeException("Private world smoke "+role+" step "+step,e);}}
 private static void varint(java.io.OutputStream out,int n)throws Exception{do{int b=n&127;n>>>=7;out.write(n==0?b:b|128);}while(n!=0);}
 private static int varint(java.io.InputStream in)throws Exception{int n=0;for(int i=0;i<5;i++){int b=in.read();if(b<0)throw new java.io.EOFException();n|=(b&127)<<(7*i);if((b&128)==0)return n;}throw new IllegalArgumentException();}
 private static void string(java.io.OutputStream out,String s)throws Exception{byte[] b=s.getBytes(java.nio.charset.StandardCharsets.UTF_8);varint(out,b.length);out.write(b);}
 private static boolean spoofOwner(String name,UUID id,int port){try(var socket=new java.net.Socket("127.0.0.1",port)){socket.setSoTimeout(10000);var out=socket.getOutputStream();var b=new java.io.ByteArrayOutputStream();varint(b,0);varint(b,net.minecraft.SharedConstants.getCurrentVersion().protocolVersion());string(b,"127.0.0.1");b.write(port>>8);b.write(port&255);varint(b,2);varint(out,b.size());b.writeTo(out);b.reset();varint(b,0);string(b,name);var data=new java.io.DataOutputStream(b);data.writeLong(id.getMostSignificantBits());data.writeLong(id.getLeastSignificantBits());varint(out,b.size());b.writeTo(out);out.flush();int length=varint(socket.getInputStream());if(length>4096)return false;return new String(socket.getInputStream().readNBytes(length),java.nio.charset.StandardCharsets.UTF_8).contains("This identity belongs to the world owner");}catch(Exception e){return false;}}

}
