package dev.unbox.client;

import com.google.gson.*;
import net.minecraft.client.Minecraft;
import net.minecraft.client.Screenshot;
import net.minecraft.client.gui.components.AbstractWidget;
import net.minecraft.server.players.NameAndId;
import java.net.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;

/** Isolated development test only. No cloud identities, credentials or external relays. */
final class SocialSmokeTest {
 private static int step;private static long last;private static CompletableFuture<String> probe;private static String expected;private static long relayWait;private static CompletableFuture<String> localProbe;private static final List<String> checks=new ArrayList<>();
 private static void check(boolean p,String s){if(!p)throw new IllegalStateException(s);checks.add(s);}
 private static void fixture(Minecraft mc)throws Exception{JsonObject v=new JsonObject();v.addProperty("updated",System.currentTimeMillis());v.addProperty("connected",true);JsonObject me=new JsonObject();me.addProperty("id","self");v.add("self",me);JsonArray friends=new JsonArray();for(int i=0;i<7;i++){JsonObject f=new JsonObject();f.addProperty("id",new UUID(0,i+1).toString());f.addProperty("uuid",new UUID(0,i+1).toString().replace("-",""));f.addProperty("name","Friend"+(i+1));f.addProperty("kind","microsoft");f.addProperty("accepted",1);f.addProperty("online",i%2==0);f.addProperty("state",i%2==0?"Playing":"Offline");friends.add(f);}v.add("friends",friends);v.add("invites",new JsonArray());Files.writeString(mc.gameDirectory.toPath().resolve("unbox-social-view.json"),v.toString());SocialBridge.view=v;}
 @SuppressWarnings("unchecked")static void tick(Minecraft mc){if(!Boolean.getBoolean("unbox.socialSmoke")||mc.player==null)return;mc.getFramerateLimitTracker().onInputReceived();long now=System.currentTimeMillis();if(now-last<1500)return;last=now;
 try{switch(step++){
 case 0->{fixture(mc);mc.setScreen(new UnboxHomeScreen(true));}
 case 1->{check(mc.screen instanceof UnboxHomeScreen,"Friends remain on quick menu before Mods");check(mc.screen.children().stream().filter(w->w instanceof AbstractWidget a&&a.getMessage().getString().equals("Invite")).count()==5,"Five friends per page with invitation controls");Screenshot.grab(mc.gameDirectory,"unbox-friends.png",mc.getMainRenderTarget(),1,c->{});SocialBridge.invite(new UUID(0,1).toString());check(!mc.getSingleplayerServer().isPublished(),"Offline account cannot publish an authenticated invitation world");check(SocialBridge.message.contains("Microsoft"),"Unsupported identity has an actionable message");mc.options.guiScale().set(6);mc.resizeGui();}
 case 2->{var home=(UnboxHomeScreen)mc.screen;for(var child:home.children())if(child instanceof AbstractWidget w)check((w.getX()+w.getWidth())*home.menuScale()<=home.width+1,"Friend control stays within scaled viewport");Screenshot.grab(mc.gameDirectory,"unbox-friends-gui6.png",mc.getMainRenderTarget(),1,c->{});mc.options.guiScale().set(2);mc.resizeGui();InetAddress address=null;for(var ni:Collections.list(NetworkInterface.getNetworkInterfaces()))if(ni.isUp())for(var a:Collections.list(ni.getInetAddresses()))if(a instanceof Inet4Address&&a.isSiteLocalAddress())address=a;if(address==null)throw new IllegalStateException("LAN interface required for probe test");final InetAddress lan=address;var socket=new DatagramSocket(0);socket.setSoTimeout(5000);String token="a".repeat(64);JsonObject r=new JsonObject();r.addProperty("probeToken",token);r.addProperty("probePort",socket.getLocalPort());r.addProperty("port",25565);JsonArray addresses=new JsonArray();addresses.add(lan.getHostAddress());r.add("lan",addresses);expected=lan.getHostAddress()+":25565";Thread.ofVirtual().start(()->{try(socket){var packet=new DatagramPacket(new byte[128],128);socket.receive(packet);byte[] wrong="UNBOX!wrong".getBytes();socket.send(new DatagramPacket(wrong,wrong.length,packet.getSocketAddress()));byte[] answer=("UNBOX!"+token).getBytes();socket.send(new DatagramPacket(answer,answer.length,packet.getSocketAddress()));}catch(Exception ignored){}});probe=CompletableFuture.supplyAsync(()->SocialBridge.probe(r));}
 case 3->{check(probe.isDone()&&expected.equals(probe.join()),"LAN UDP nonce probe ignores wrong response and selects direct address");var server=mc.getSingleplayerServer();int port;try(var s=new java.net.ServerSocket(0)){port=s.getLocalPort();}server.getConnection().startTcpServerListener(InetAddress.getLoopbackAddress(),port);var h=SocialBridge.class.getDeclaredField("handler");h.setAccessible(true);var g=SocialBridge.class.getDeclaredField("group");g.setAccessible(true);check(h.get(null)!=null&&g.get(null)!=null,"Actual Netty listener is captured for on-demand relay");check(link.e4mc.E4mcClient.session==null,"Opening a local listener does not start internet relay");var guarded=SocialBridge.class.getDeclaredField("guarded");guarded.setAccessible(true);guarded.setBoolean(null,true);var owner=SocialBridge.class.getDeclaredField("owner");owner.setAccessible(true);owner.set(null,mc.getUser().getProfileId());var invited=SocialBridge.class.getDeclaredField("INVITED");invited.setAccessible(true);Set<UUID> ids=(Set<UUID>)invited.get(null);ids.add(mc.getUser().getProfileId());UUID friend=new UUID(0,1);ids.add(friend);check(SocialBridge.allowed(friend),"Session admits explicitly invited UUID");check(server.getPlayerList().canPlayerLogin(new InetSocketAddress("127.0.0.1",25565),new NameAndId(new UUID(0,100),"Stranger"))!=null,"Actual player admission mixin rejects strangers");SocialBridge.stopSharing();check(!SocialBridge.allowed(friend)&&SocialBridge.allowed(mc.getUser().getProfileId()),"Stopping sharing revokes guests and retains host");SocialBridge.stop();}
 case 4->{if(Boolean.getBoolean("unbox.relaySmoke")){var server=mc.getSingleplayerServer();server.setUsesAuthentication(true);int relayPort;try(var ss=new java.net.ServerSocket(0)){relayPort=ss.getLocalPort();}var guarded=SocialBridge.class.getDeclaredField("guarded");guarded.setAccessible(true);guarded.setBoolean(null,true);var owner=SocialBridge.class.getDeclaredField("owner");owner.setAccessible(true);owner.set(null,mc.getUser().getProfileId());var allow=SocialBridge.class.getDeclaredField("INVITED");allow.setAccessible(true);((Set<UUID>)allow.get(null)).add(mc.getUser().getProfileId());check(server.publishServer(server.getDefaultGameType(),false,relayPort),"Isolated authenticated test world publishes normally");localProbe=CompletableFuture.supplyAsync(()->ping("127.0.0.1",relayPort));var room=SocialBridge.class.getDeclaredField("room");room.setAccessible(true);room.set(null,new JsonObject());var start=SocialBridge.class.getDeclaredMethod("startRelay");start.setAccessible(true);start.invoke(null);relayWait=now;return;}finish(mc);}
 case 5->{if(localProbe.isDone()&&!localProbe.join().contains("26.1"))throw new IllegalStateException("Local status: "+localProbe.join());var relay=SocialBridge.class.getDeclaredField("relay");relay.setAccessible(true);String domain=(String)relay.get(null);if(domain.isEmpty()&&now-relayWait<65000){step=5;return;}check(!domain.isEmpty(),"Public e4mc relay returns a real domain on this Mac");probe=CompletableFuture.supplyAsync(()->ping(domain));}
 case 6->{if(!probe.isDone()&&now-relayWait<90000){step=6;return;}String response=probe.isDone()?probe.join():"Timeout";if(!response.contains("26.1"))throw new IllegalStateException("Relay status response: "+response);check(true,"Minecraft status round-trip succeeds through real internet relay");SocialBridge.stopSharing();finish(mc);}
 default->{}
 }}catch(Exception e){SocialBridge.stopSharing();throw new RuntimeException("Social regression failed at step "+(step-1),e);}}
 private static void finish(Minecraft mc)throws Exception{Files.writeString(mc.gameDirectory.toPath().resolve("logs/social-smoke.json"),new Gson().toJson(Map.of("passed",checks.size(),"checks",checks)));mc.stop();}
 private static void number(java.io.OutputStream out,int value)throws Exception{do{int b=value&127;value>>>=7;out.write(value==0?b:b|128);}while(value!=0);}
 private static int number(java.io.InputStream in)throws Exception{int result=0;for(int i=0;i<5;i++){int b=in.read();if(b<0)throw new java.io.EOFException();result|=(b&127)<<(7*i);if((b&128)==0)return result;}throw new java.io.IOException("Invalid varint");}
 private static String ping(String domain){return ping(domain,25565);}
 private static String ping(String domain,int port){try(var socket=new Socket()){socket.connect(new InetSocketAddress(domain,port),10000);socket.setSoTimeout(10000);var buffer=new java.io.ByteArrayOutputStream();number(buffer,0);number(buffer,net.minecraft.SharedConstants.getCurrentVersion().protocolVersion());byte[] host=domain.getBytes(java.nio.charset.StandardCharsets.UTF_8);number(buffer,host.length);buffer.write(host);buffer.write(port>>8);buffer.write(port&255);number(buffer,1);var out=socket.getOutputStream();number(out,buffer.size());buffer.writeTo(out);out.write(new byte[]{1,0});out.flush();var in=socket.getInputStream();int length=number(in);if(length>65536||number(in)!=0)return "Invalid status";int size=number(in);if(size>65536)return "Invalid response";return new String(in.readNBytes(size),java.nio.charset.StandardCharsets.UTF_8);}catch(Exception e){return e.getClass().getSimpleName()+": "+e.getMessage();}}
}
