package dev.unbox.client;

import net.minecraft.client.Minecraft;
import net.minecraft.client.KeyMapping;
import net.minecraft.client.Screenshot;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.components.AbstractWidget;
import net.minecraft.client.input.KeyEvent;
import net.minecraft.client.input.MouseButtonEvent;
import net.minecraft.client.input.MouseButtonInfo;
import com.mojang.blaze3d.platform.InputConstants;
import org.lwjgl.glfw.GLFW;
import java.nio.file.*;
import java.util.*;

/** Drives real screen widgets in an isolated world; inert in ordinary game sessions. */
public final class UiSmokeTest {
    private static boolean mapKeyChecked;private static long start;private static int step,moduleIndex;private static final List<String> checks=new ArrayList<>();
    private static String originalColor,originalKey;private static int colorProbe,preciseBefore;private static int hudX,hudY;private static double originalOpacity;
    private static AbstractWidget widget(Minecraft m,String name){
        for(int attempt=0;attempt<15;attempt++){var found=m.screen.children().stream().filter(c->c instanceof AbstractWidget w&&w.visible&&w.getMessage().getString().equals(name)).findFirst();if(found.isPresent())return (AbstractWidget)found.get();if(!(m.screen instanceof UnboxScreen))break;m.screen.mouseScrolled(m.getWindow().getGuiScaledWidth()/2.,m.getWindow().getGuiScaledHeight()/2.,0,-2);}
        return m.screen.children().stream().filter(c->c instanceof AbstractWidget w&&w.visible&&w.getMessage().getString().equals(name)).map(c->(AbstractWidget)c).findFirst().orElseThrow(()->new IllegalStateException("Missing visible control: "+name));}
    private static MouseButtonEvent mouse(double x,double y){return new MouseButtonEvent(x,y,new MouseButtonInfo(0,0));}
    private static void click(Minecraft m,String name){var w=widget(m,name);float scale=m.screen instanceof UnboxScreen u?u.menuScale():m.screen instanceof UnboxHomeScreen h?h.menuScale():1;float offset=m.screen instanceof UnboxScreen u?u.menuOffsetY():m.screen instanceof UnboxHomeScreen h?h.menuOffsetY():0;var e=mouse((w.getX()+Math.min(12,w.getWidth()/2))*scale,(w.getY()+Math.min(13,w.getHeight()/2)+offset)*scale);if(!m.screen.mouseClicked(e,false))throw new IllegalStateException("Click not handled: "+name);m.screen.mouseReleased(e);}
    private static void key(Minecraft m,int key){m.screen.keyPressed(new KeyEvent(key,0,0));}
    private static void search(Minecraft m,String value){if(m.screen instanceof UnboxHomeScreen)click(m,"MODS");for(var child:m.screen.children())if(child instanceof EditBox box&&box.getMessage().getString().equals("Search mods")){box.setValue(value);return;}throw new IllegalStateException("Missing search");}
    private static void check(boolean pass,String label){if(!pass)throw new IllegalStateException(label);checks.add(label);}
    private static double teleportX,teleportZ;
    private static void shot(Minecraft m,String name){Screenshot.grab(m.gameDirectory,"unbox-"+name+".png",m.getMainRenderTarget(),1,c->{});}
    private static final class ParticleProbe extends net.minecraft.client.renderer.state.level.QuadParticleRenderState {
        int color;
        @Override public void add(net.minecraft.client.particle.SingleQuadParticle.Layer layer,float x,float y,float z,float qx,float qy,float qz,float qw,float size,float u0,float u1,float v0,float v1,int color,int light){this.color=color;}
    }
    public static void tick(Minecraft m){
        if(!Boolean.getBoolean("unbox.uiSmoke")||m.player==null)return;
        m.getFramerateLimitTracker().onInputReceived();
        long now=System.currentTimeMillis();if(start==0)start=now;if(now-start<(step==0?5000:900))return;
        start=now;
        try{
            switch(step++){
                case 0 -> {Path fixture=m.gameDirectory.toPath().resolve("ui-friends-fixture.json");if(Files.exists(fixture))SocialBridge.view=com.google.gson.JsonParser.parseString(Files.readString(fixture)).getAsJsonObject();KeyMapping.click(InputConstants.Type.KEYSYM.getOrCreate(GLFW.GLFW_KEY_RIGHT_SHIFT));}
                case 1 -> {check(m.screen instanceof UnboxHomeScreen,"Right Shift opens the quick menu first");if(!SocialBridge.rows("friends").isEmpty())check(!SocialBridge.flag(SocialBridge.rows("friends").getFirst(),"online"),"Offline friend remains visible without connection");shot(m,"shift-home");click(m,"MODS");check(m.screen instanceof UnboxScreen,"Mods opens from quick menu");click(m,"HUD");check(m.screen.children().stream().noneMatch(c->c instanceof AbstractWidget w&&w.visible&&w.getMessage().getString().equals("Crosshair")),"HUD category filters");click(m,"All");click(m,"Favorite Crosshair");click(m,"Favorites");widget(m,"Crosshair");check(true,"Favorites filter and persist");click(m,"All");search(m,"Crosshair");}
                case 2 -> {shot(m,"mod-search");click(m,"Crosshair");boolean before=UnboxClient.enabled("crosshair");click(m,"Toggle Crosshair");check(before!=UnboxClient.enabled("crosshair"),"Independent module toggle");var slider=widget(m,"Thickness");slider.keyPressed(new KeyEvent(GLFW.GLFW_KEY_HOME,0,0));slider.keyPressed(new KeyEvent(GLFW.GLFW_KEY_RIGHT,0,0));slider.keyPressed(new KeyEvent(GLFW.GLFW_KEY_RIGHT,0,0));check(UnboxClient.number("crosshair.thickness",1,1,5)==3,"Keyboard slider adjustment");click(m,"Center dot");}
                case 3 -> {shot(m,"mod-settings");originalColor=ClientHud.value("crosshair.color","#FFFFFF");click(m,"Choose Color");click(m,"#7DC8FF");check(ClientHud.value("crosshair.color","").equals("#7DC8FF"),"Color picker live update");}
                case 4 -> {shot(m,"color-picker");click(m,"Cancel");check(ClientHud.value("crosshair.color","").equals(originalColor),"Color cancel restores value");click(m,"Choose Color");click(m,"#7DC8FF");click(m,"Done");click(m,"Reset settings");check(UnboxClient.number("crosshair.thickness",1,1,5)==1,"Module reset");click(m,"Undo reset");check(UnboxClient.number("crosshair.thickness",1,1,5)==3,"Reset undo");m.screen.mouseScrolled(m.screen.width/2,m.screen.height/2,0,-20);widget(m,"Attack cooldown");check(true,"Settings scroll reaches last control");click(m,"Back");search(m,"Zoom");click(m,"Zoom");originalKey=UnboxClient.zoomKey.saveString();click(m,"Change keybind");key(m,GLFW.GLFW_KEY_W);check(UnboxClient.zoomKey.matches(new KeyEvent(GLFW.GLFW_KEY_W,0,0)),"Conflicting movement key reassigned");check(m.options.keyUp.isUnbound(),"Previous binding cleared");click(m,"Change keybind");key(m,GLFW.GLFW_KEY_F8);check(UnboxClient.zoomKey.matches(new KeyEvent(GLFW.GLFW_KEY_F8,0,0)),"Keybind recorder saves new key");}
                case 5 -> {shot(m,"zoom-settings");key(m,GLFW.GLFW_KEY_RIGHT_SHIFT);check(m.screen==null,"Right Shift closes panel");UnboxClient.zoomKey.setDown(true);}
                case 6 -> {check(UnboxClient.zooming(),"Zoom responds to registered key");check(UnboxClient.zoomFactor()>1,"Zoom affects rendered field of view");UnboxClient.zoomKey.setDown(false);}
                case 7 -> {check(!UnboxClient.zooming(),"Hold zoom releases");KeyMapping.click(InputConstants.Type.KEYSYM.getOrCreate(GLFW.GLFW_KEY_RIGHT_SHIFT));}
                case 8 -> {if(m.screen instanceof UnboxHomeScreen)click(m,"MODS");UnboxClient.set("cps",true);var original=ClientHud.bounds("cps",m.screen.width,m.screen.height,true);m.screen.mouseClicked(mouse(original.x()+10,original.y()+10),false);m.screen.mouseDragged(mouse(original.x()+50,original.y()+30),40,20);m.screen.mouseReleased(mouse(original.x()+50,original.y()+30));check(ClientHud.bounds("cps",m.screen.width,m.screen.height,true).x()==original.x()+40,"HUD drags directly from Shift panel");UnboxClient.CONFIG.remove("cps.x");UnboxClient.CONFIG.remove("cps.y");click(m,"Edit HUD");hudX=ClientHud.bounds("fps",m.screen.width,m.screen.height,true).x();hudY=ClientHud.bounds("fps",m.screen.width,m.screen.height,true).y();var b=ClientHud.bounds("fps",m.screen.width,m.screen.height,true);var other=ClientHud.bounds("coordinates",m.screen.width,m.screen.height,true);m.screen.mouseClicked(mouse(b.x()+8,b.y()+8),false);m.screen.mouseDragged(mouse(b.x()+168,b.y()+88),160,80);m.screen.mouseReleased(mouse(b.x()+168,b.y()+88));check(ClientHud.bounds("fps",m.screen.width,m.screen.height,true).x()!=hudX,"HUD drag moves selected element");check(ClientHud.bounds("coordinates",m.screen.width,m.screen.height,true).equals(other),"Other HUD elements remain independent");}
                case 9 -> {shot(m,"hud-editor");click(m,"Cancel");check(ClientHud.bounds("fps",m.screen.width,m.screen.height,true).x()==hudX,"HUD cancel restores position");click(m,"Edit HUD");var b=ClientHud.bounds("fps",m.screen.width,m.screen.height,true);m.screen.mouseClicked(mouse(b.x()+b.w(),b.y()+b.h()),false);m.screen.mouseDragged(mouse(b.x()+b.w()*1.5,b.y()+b.h()*1.5),10,10);m.screen.mouseReleased(mouse(b.x(),b.y()));check(ClientHud.scale("fps")>1,"HUD corner resize");click(m,"Done");check(UnboxClient.CONFIG.containsKey("fps.scale"),"HUD Done keeps changes");search(m,"FPS");click(m,"FPS");click(m,"Appearance");}
                case 10 -> {shot(m,"hud-appearance");check(m.screen.children().stream().noneMatch(c->c instanceof AbstractWidget w&&w.getMessage().getString().equals("Background")),"FPS always has no background control");click(m,"Back");search(m,"");moduleIndex=0;}
                case 11 -> {if(moduleIndex<ModOptions.MODS.size()){var mod=ModOptions.MODS.get(moduleIndex++);search(m,mod.title());click(m,mod.title());step=12;}else step=14;}
                case 12 -> {var mod=ModOptions.MODS.get(moduleIndex-1);shot(m,"module-"+mod.id());if(mod.id().equals("freelook"))widget(m,"Change keybind");check(true,"Rendered "+mod.id()+" settings");if(mod.id().equals("performance")){click(m,"Open video settings");step=13;}else{click(m,"Back");step=11;}}
                case 13 -> {check(m.screen.getClass().getName().contains("sodium"),"Performance opens Sodium settings");shot(m,"sodium-settings");m.screen.onClose();click(m,"Back");step=11;}
                case 14 -> {search(m,"");m.options.guiScale().set(4);m.resizeGui();}
                case 15 -> {shot(m,"compact-panel");search(m,"Chat");click(m,"Chat");originalOpacity=m.options.textBackgroundOpacity().get();click(m,"Toggle Chat");m.gui.getChat().addClientSystemMessage(net.minecraft.network.chat.Component.literal("Unbox chat renderer test"));}
                case 16 -> {shot(m,"compact-chat");check(m.options.textBackgroundOpacity().get()==originalOpacity,"Chat does not modify global background opacity");m.options.guiScale().set(2);m.resizeGui();key(m,GLFW.GLFW_KEY_RIGHT_SHIFT);}
                case 17 -> {KeyMapping.click(InputConstants.Type.KEYSYM.getOrCreate(GLFW.GLFW_KEY_RIGHT_SHIFT));m.options.guiScale().set(6);m.resizeGui();}
                case 18 -> {shot(m,"large-gui-panel");search(m,"Crosshair");click(m,"Crosshair");var slider=widget(m,"Thickness");int before=UnboxClient.number("crosshair.thickness",1,1,5);slider.keyPressed(new KeyEvent(GLFW.GLFW_KEY_RIGHT,0,0));check(UnboxClient.number("crosshair.thickness",1,1,5)==before+1,"Scaled menu controls remain functional");slider.keyPressed(new KeyEvent(GLFW.GLFW_KEY_LEFT,0,0));}
                case 19 -> {shot(m,"large-gui-settings");m.options.guiScale().set(2);m.resizeGui();key(m,GLFW.GLFW_KEY_RIGHT_SHIFT);}
                case 20 -> {UnboxClient.set("particles",true);UnboxClient.set("particles.density",0);
                    var particle=m.particleEngine.createParticle(net.minecraft.core.particles.ParticleTypes.FLAME,m.player.getX(),m.player.getY(),m.player.getZ(),0,0,0);
                    check(particle!=null&&!ParticleFilter.allow(particle),"Zero density filters real particle");UnboxClient.set("particles.density",100);UnboxClient.set("particles.flame",false);check(!ParticleFilter.allow(particle),"Flame family filter");UnboxClient.set("particles.flame",true);check(ParticleFilter.allow(particle),"Full density preserves enabled family");UnboxClient.save();
                    Properties disk=new Properties();try(var in=Files.newInputStream(m.gameDirectory.toPath().resolve("config/unbox.properties"))){disk.load(in);}check(disk.getProperty("crosshair.thickness").equals("3"),"Settings persist on disk");check(disk.getProperty("favorite.crosshair").equals("true"),"Favorites persist on disk");check(!CrosshairPattern.importCode("UNBOX1:bad"),"Crosshair import rejects invalid data");CrosshairPattern.paint(7,7,true);check(CrosshairPattern.pixels().charAt(112)=='1',"Custom crosshair canvas writes a pixel");check(CrosshairPattern.importCode(CrosshairPattern.share()),"Custom crosshair sharing round trip");UnboxClient.set("crosshair.shape","Cross");UnboxClient.click(0);check(UnboxClient.clickLight(0)>.8,"CPS click immediately lights its key");shot(m,"gameplay");
                    UnboxClient.set("particles.flame.lifetime",50);int life=particle.getLifetime();ParticleFilter.customize(particle);check(particle.getLifetime()==Math.max(1,life/2),"Particle lifetime applies to actual game particles");UnboxClient.CONFIG.remove("particles.flame.lifetime");
                }
                case 21 -> {KeyMapping.click(InputConstants.Type.KEYSYM.getOrCreate(GLFW.GLFW_KEY_RIGHT_SHIFT));}
                case 22 -> {search(m,"Crosshair");click(m,"Crosshair");click(m,"Canvas");click(m,"Crosshair canvas");check(ClientHud.value("crosshair.shape","").equals("Custom"),"Canvas UI selects custom crosshair");}
                case 23 -> {shot(m,"crosshair-canvas");click(m,"Copy design");check(m.keyboardHandler.getClipboard().startsWith("UNBOX1:"),"Canvas copies a share code");click(m,"Clear canvas");check(!CrosshairPattern.pixels().contains("1"),"Canvas clear action");click(m,"Paste design");check(CrosshairPattern.pixels().contains("1"),"Canvas paste restores design");click(m,"Behavior");check(!widget(m,"Choose Target color").active,"Dependent target color is disabled");click(m,"Target color");check(widget(m,"Choose Target color").active,"Target color dependency updates immediately");}
                case 24 -> {shot(m,"crosshair-behavior");click(m,"Back");search(m,"Particles");click(m,"Particles");click(m,"Types");click(m,"Particle type");key(m,GLFW.GLFW_KEY_DOWN);key(m,GLFW.GLFW_KEY_ENTER);check(ModOptions.particleFamily().equals("smoke"),"Particle type selector changes the edited family");click(m,"Custom color");check(widget(m,"Choose Particle color").active,"Particle tint dependency updates");}
                case 25 -> {shot(m,"particle-types");click(m,"Back");search(m,"");for(String id:List.of("fps","cps","armor")){var b=ClientHud.bounds(id,m.screen.width,m.screen.height,true);int y=b.y();m.screen.mouseClicked(mouse(b.x()+5,b.y()+5),false);m.screen.mouseDragged(mouse(b.x()+5,b.y()+20),0,15);m.screen.mouseReleased(mouse(b.x()+5,b.y()+20));check(ClientHud.bounds(id,m.screen.width,m.screen.height,true).y()==y+15,"Direct dragging works for "+id);}UnboxClient.set("fps.locked",true);var b=ClientHud.bounds("fps",m.screen.width,m.screen.height,true);m.screen.mouseClicked(mouse(b.x()+4,b.y()+4),false);m.screen.mouseDragged(mouse(b.x()+20,b.y()+20),16,16);m.screen.mouseReleased(mouse(b.x()+20,b.y()+20));check(ClientHud.bounds("fps",m.screen.width,m.screen.height,true).equals(b),"Locked HUD ignores dragging");UnboxClient.set("fps.locked",false);}
                case 26 -> {search(m,"Crosshair");click(m,"Crosshair");click(m,"Presets");click(m,"Ring");check(ClientHud.value("crosshair.shape","").equals("Custom")&&CrosshairPattern.pixels().equals(CrosshairPattern.preset(3)),"Visual preset selects the actual rendered pattern");}
                case 27 -> {shot(m,"presets");click(m,"Canvas");var canvas=widget(m,"Crosshair canvas");float scale=((UnboxScreen)m.screen).menuScale();var point=new MouseButtonEvent((canvas.getX()+7*13+6)*scale,(canvas.getY()+7*13+6)*scale,new MouseButtonInfo(0,0));m.screen.mouseClicked(point,false);m.screen.mouseReleased(point);check(CrosshairPattern.pixels().charAt(112)=='1',"Canvas paints the center with left click");var erase=new MouseButtonEvent(point.x(),point.y(),new MouseButtonInfo(1,0));check(m.screen.mouseClicked(erase,false),"Canvas accepts right mouse erase");m.screen.mouseReleased(erase);check(CrosshairPattern.pixels().charAt(112)=='0',"Right click erases without painting");click(m,"General");((EditBox)widget(m,"Search settings")).setValue("rotation");widget(m,"Rotation");check(true,"Settings search finds an option in another tab");var slider=widget(m,"Rotation");preciseBefore=UnboxClient.number("crosshair.rotation",0,-180,180);var number=mouse((slider.getX()+slider.getWidth()-10)*scale,(slider.getY()+12)*scale);m.screen.mouseClicked(number,false);m.screen.mouseReleased(number);((EditBox)widget(m,"Value")).setValue("999");click(m,"Apply value");widget(m,"Value");check(UnboxClient.number("crosshair.rotation",0,-180,180)==preciseBefore,"Out-of-range numeric input cannot change the setting");((EditBox)widget(m,"Value")).setValue("45");key(m,GLFW.GLFW_KEY_ENTER);check(UnboxClient.number("crosshair.rotation",0,-180,180)==45,"Exact numeric entry commits on Enter");}
                case 28 -> {shot(m,"settings-search");var slider=widget(m,"Rotation");float scale=((UnboxScreen)m.screen).menuScale();m.screen.mouseClicked(new MouseButtonEvent((slider.getX()+12)*scale,(slider.getY()+12)*scale,new MouseButtonInfo(1,0)),false);check(UnboxClient.number("crosshair.rotation",0,-180,180)==0,"Right click resets only the selected setting");((EditBox)widget(m,"Search settings")).setValue("");click(m,"Choose Color");originalColor=ClientHud.value("crosshair.color","");((EditBox)widget(m,"Hex color")).setValue("#ABCDEF");check(ClientHud.value("crosshair.color","").equals("#ABCDEF"),"Hex input updates the color model");((EditBox)widget(m,"Hex color")).setValue("#GGGGGG");check(ClientHud.value("crosshair.color","").equals("#ABCDEF"),"Invalid hex input leaves the last valid color");widget(m,"Saturation and brightness").keyPressed(new KeyEvent(GLFW.GLFW_KEY_DOWN,0,0));check(!ClientHud.value("crosshair.color","").equals("#ABCDEF"),"Color plane supports keyboard adjustment");key(m,GLFW.GLFW_KEY_ESCAPE);check(ClientHud.value("crosshair.color","").equals(originalColor),"Escape cancels all color edits");click(m,"Back");search(m,"Particles");click(m,"Particles");}
                case 29 -> {shot(m,"particle-overview");click(m,"Edit Enchant");check(ModOptions.particleFamily().equals("enchant"),"Particle overview opens the matching settings");check(widget(m,"Opacity %").active,"Particle opacity is editable");var flame=m.particleEngine.createParticle(net.minecraft.core.particles.ParticleTypes.FLAME,m.player.getX(),m.player.getY(),m.player.getZ(),0,0,0);var enchant=m.particleEngine.createParticle(net.minecraft.core.particles.ParticleTypes.ENCHANTED_HIT,m.player.getX(),m.player.getY(),m.player.getZ(),0,0,0);check(((ParticleAccess)flame).unboxFamily().equals("particles.flame"),"Registry tags real flame particles");check(((ParticleAccess)enchant).unboxFamily().equals("particles.enchant"),"Enchanted hit is distinct from critical hit");UnboxClient.set("particles.enchant",false);check(!ParticleFilter.allow(enchant)&&ParticleFilter.allow(flame),"Particle families toggle independently");UnboxClient.set("particles.enchant",true);UnboxClient.set("particles.flame.opacity",25);var quad=(net.minecraft.client.particle.SingleQuadParticle)flame;var state=new ParticleProbe();quad.extract(state,m.gameRenderer.getMainCamera(),0);check((state.color>>>24)>=62&&(state.color>>>24)<=64,"Particle opacity reaches actual render-state alpha");UnboxClient.set("particles.flame.opacity",100);quad.extract(state,m.gameRenderer.getMainCamera(),0);check((state.color>>>24)==255,"Opacity extraction restores vanilla alpha for the next frame");click(m,"Back");search(m,"Armor Status");click(m,"Armor Status");click(m,"Item names");UnboxClient.set("armor.format","Remaining / Max");int[] cell=ClientHud.armorCell(true);check(cell[0]>=PanelStyle.hudWidth("Diamond Chestplate")+21,"Armor layout expands to fit actual item names");check(ClientHud.durability(ClientHud.equipment(true).getFirst()).contains(" / "),"Remaining and maximum durability are formatted separately");}
                case 30 -> {shot(m,"armor-expanded");click(m,"Equipment");int before=ClientHud.equipment(true).size();click(m,"Offhand");check(ClientHud.equipment(true).size()==before+1,"Offhand selection adds the shield slot");click(m,"Helmet");check(ClientHud.equipment(true).size()==before,"Equipment slot toggles change the actual HUD data");click(m,"Back");search(m,"Keystrokes");click(m,"Keystrokes");click(m,"Toggle Keystrokes");int[] beforeSize=KeystrokesHud.size();click(m,"Movement keys");check(KeystrokesHud.size()[1]<beforeSize[1],"Hidden movement keys remove their layout space");click(m,"Movement keys");check(KeystrokesHud.light(0,true)==1,"Keystroke press lights immediately");check(KeystrokesHud.light(0,false)>.9,"Keystroke release starts a fade");}
                case 31 -> {shot(m,"keystrokes-expanded");click(m,"Appearance");click(m,"Choose Pressed background");click(m,"#7DC8FF");click(m,"Done");check(ClientHud.value("keystrokes.pressColor","").equals("#7DC8FF"),"Keystrokes use independently saved pressed colors");click(m,"Back");search(m,"Freelook");click(m,"Freelook");click(m,"Invert horizontal");click(m,"Invert vertical");check(ClientHud.flag("freelook.invertX",false)&&ClientHud.flag("freelook.invertY",false),"Freelook inversion controls persist");}
                case 32 -> {shot(m,"freelook-expanded");key(m,GLFW.GLFW_KEY_RIGHT_SHIFT);UnboxClient.set("zoom",true);UnboxClient.set("zoom.mode","Hold");UnboxClient.zoomKey.setDown(true);int factor=UnboxClient.number("zoom.factor",3,2,12);check(UnboxClient.adjustZoom(1)&&UnboxClient.number("zoom.factor",3,2,12)==factor+1,"Zoom scroll adjusts actual magnification");UnboxClient.set("zoom.scroll",false);check(!UnboxClient.adjustZoom(1),"Disabled zoom scrolling lets vanilla scroll continue");UnboxClient.zoomKey.setDown(false);UnboxClient.set("zoom.scroll",true);UnboxClient.set("freelook",true);Freelook.activate(true);var renderedCamera=m.gameRenderer.getMainCamera();var align=net.minecraft.client.Camera.class.getDeclaredMethod("alignWithEntity",float.class);align.setAccessible(true);align.invoke(renderedCamera,1f);Freelook.rotation(0,0);float yaw=m.player.getYRot();var dx=net.minecraft.client.MouseHandler.class.getDeclaredField("accumulatedDX");var dy=net.minecraft.client.MouseHandler.class.getDeclaredField("accumulatedDY");dx.setAccessible(true);dy.setAccessible(true);dx.setDouble(m.mouseHandler,30);dy.setDouble(m.mouseHandler,30);var turn=net.minecraft.client.MouseHandler.class.getDeclaredMethod("turnPlayer",double.class);turn.setAccessible(true);turn.invoke(m.mouseHandler,.016);check(Freelook.yaw()<0&&Freelook.pitch()<0,"Freelook inversion affects actual camera motion");check(m.player.getYRot()==yaw,"Freelook preserves the player rotation");align.invoke(renderedCamera,1f);check(Math.abs(renderedCamera.yRot()-Freelook.yaw())<.01f&&Math.abs(renderedCamera.xRot()-Freelook.pitch())<.01f,"Freelook controls the actual rendered camera");dx.setDouble(m.mouseHandler,0);dy.setDouble(m.mouseHandler,0);Freelook.activate(false);UnboxClient.set("freelook",false);UnboxClient.set("coordinates.biome",true);UnboxClient.set("coordinates.dimension",true);UnboxClient.set("coordinates.nether",true);}
                case 33 -> {ClientHud.update(0,0);check(ClientHud.lines("coordinates").stream().anyMatch(v->v.startsWith("Nether "))||m.level.dimension().equals(net.minecraft.world.level.Level.END),"Coordinates include dimension conversion");KeyMapping.click(InputConstants.Type.KEYSYM.getOrCreate(GLFW.GLFW_KEY_RIGHT_SHIFT));}
                case 34 -> {search(m,"Particles");click(m,"Particles");m.options.guiScale().set(6);m.resizeGui();}
                case 35 -> {shot(m,"particle-overview-gui6");click(m,"Edit Totem");check(ModOptions.particleFamily().equals("totem"),"Last particle tile remains reachable at GUI 6");m.options.guiScale().set(2);m.resizeGui();click(m,"Back");search(m,"");}
                case 36 -> {shot(m,"final-panel");m.screen.onClose();check(m.screen instanceof UnboxHomeScreen,"Closing the Mods browser returns to quick menu");var b=ClientHud.bounds("cps",m.screen.width,m.screen.height,true);int before=b.x();m.screen.mouseClicked(mouse(b.x()+5,b.y()+5),false);m.screen.mouseDragged(mouse(b.x()+20,b.y()+5),15,0);m.screen.mouseReleased(mouse(b.x()+20,b.y()+5));check(ClientHud.bounds("cps",m.screen.width,m.screen.height,true).x()==before+15,"HUD drags directly from the quick menu");click(m,"Game settings");check(m.screen instanceof net.minecraft.client.gui.screens.options.OptionsScreen,"Quick menu opens real game settings");m.screen.onClose();click(m,"Edit HUD");check(m.screen instanceof UnboxScreen u&&u.isEditingHud(),"Quick menu opens HUD editor directly");click(m,"Cancel");key(m,GLFW.GLFW_KEY_RIGHT_SHIFT);check(m.screen==null,"Right Shift exits the menu hierarchy to gameplay");}
                case 37 -> {UnboxClient.set("minimap",true);UnboxClient.set("ping",true);KeyMapping.set(InputConstants.Type.KEYSYM.getOrCreate(GLFW.GLFW_KEY_M),true);KeyMapping.click(InputConstants.Type.KEYSYM.getOrCreate(GLFW.GLFW_KEY_M));check(ClientHud.IDS.contains("minimap")&&ClientHud.IDS.contains("ping"),"Map and ping participate in HUD editor");check(ClientHud.lines("ping").getFirst().equals("Local"),"Singleplayer latency is labelled Local");WorldMap.death(new WorldMap.Death(m.player.getUUID(),"Self",m.level.dimension().identifier().toString(),m.player.getBlockX()+10,m.player.getBlockY(),m.player.getBlockZ()+10,1));WorldMap.death(new WorldMap.Death(java.util.UUID.fromString("00000000-0000-0000-0000-000000000002"),"Teammate",m.level.dimension().identifier().toString(),m.player.getBlockX()-10,m.player.getBlockY(),m.player.getBlockZ()-10,2));}
                case 38 -> {if(!mapKeyChecked){check(m.screen instanceof WorldMap.MapScreen,"M key opens full map through native key mapping");mapKeyChecked=true;KeyMapping.set(InputConstants.Type.KEYSYM.getOrCreate(GLFW.GLFW_KEY_M),false);}if(WorldMap.cursor<12000){step--;break;}check(WorldMap.texture!=null,"Map texture created from loaded terrain");shot(m,"world-map");key(m,GLFW.GLFW_KEY_M);check(m.screen==null,"M closes full map");WorldMap.open();var map=(WorldMap.MapScreen)m.screen;var marker=WorldMap.DEATHS.values().stream().filter(d->d.time()==1).findFirst().orElseThrow();double px=map.x+(marker.x()-WorldMap.originX)*map.size/(double)(WorldMap.RES*WorldMap.step),py=map.y+(marker.z()-WorldMap.originZ)*map.size/(double)(WorldMap.RES*WorldMap.step);var permissions=m.player.permissions();m.player.setPermissions(net.minecraft.server.permissions.PermissionSet.NO_PERMISSIONS);m.screen.mouseClicked(mouse(px,py),true);check(m.screen==map&&map.notice.contains("requires"),"Double-click teleport denied without cheat permission");m.player.setPermissions(permissions);if(WorldMap.canTeleport()){teleportX=marker.x()+.5;teleportZ=marker.z()+.5;m.screen.mouseClicked(mouse(px,py),true);check(m.screen==null,"Permitted death teleport submits command and closes map");}else m.screen.onClose();check(WorldMap.DEATHS.size()>=2,"Both own and teammate deaths retained");UnboxClient.set("minimap.scale",150);check(ClientHud.bounds("minimap",m.getWindow().getGuiScaledWidth(),m.getWindow().getGuiScaledHeight(),true).w()==Math.round(192*ClientHud.unit()),"Minimap HUD resizes through shared layout");}
                case 39 -> {if(teleportX!=0)check(Math.abs(m.player.getX()-teleportX)<1&&Math.abs(m.player.getZ()-teleportZ)<1,"Server executes permitted death-marker teleport");shot(m,"minimap-hud");Files.writeString(m.gameDirectory.toPath().resolve("logs/ui-smoke.json"),"{\"passed\":"+checks.size()+",\"checks\":["+checks.stream().map(s->"\""+s+"\"").reduce((a,b)->a+","+b).orElse("")+"]}");m.stop();}
                default -> {}
            }
        }catch(Exception e){throw new RuntimeException("Unbox UI regression failed at step "+(step-1),e);}
    }
}
